name: Setup
description: Setup the repo
runs:
  using: "composite"
  steps:
      - uses: pnpm/action-setup@v2.2.4
      - name: Use Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
        shell: bash
