[[headers]]
for = "/manifest.webmanifest"
[headers.values]
Content-Type = "application/manifest+json"
[dev]
targetPort = 8888
command = "pnpm run dev:vite"
port = 5173
[build]
command = "pnpm run build"
publish = "dist"
